apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfs-cs-deployment
  labels:
    app.kubernetes.io/name: cs
    app: cs
  namespace: tfs-cs
  annotations:
    linkerd.io/inject: enabled
spec:
  selector:
    matchLabels:
      app: cs
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cs
    spec:
      containers:
        - name: syllo-cs
          image: 309602515679.dkr.ecr.eu-west-1.amazonaws.com/syllo-cs:1.8.3
          imagePullPolicy: Always
          resources:
            limits:
              memory: 1Gi
              cpu: "0.7"
            requests:
              memory: 600Mi
              cpu: "0.4"
          ports:
            - containerPort: 10003
          env:
            - name: npm_package_version
              value: "1.8.3"
            - name: ENVIRONMENT
              value: "production"
            - name: GRPC_SERVER_URL
              value: "0.0.0.0:10003"
            - name: HTTP_SERVER_PORT
              value: "1111"
            - name: PUBSUB_URL
              valueFrom:
                secretKeyRef:
                  name: cs-secrets
                  key: redis-url
            - name: AS_URL
              value: "172.20.49.111:10004"
            - name: ELS_URL
              value: "172.20.185.160:10006"
            - name: MPS_URL
              value: "172.20.255.222:10005"
            - name: FS_URL
              value: "172.20.142.166:10007"
            - name: CONFIG_URL
              value: "172.20.176.186:10008"
            - name: MODULR_API_URL
              value: "https://api-sandbox.modulrfinance.com/api-sandbox"
            - name: MODULR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cs-secrets
                  key: modulr-api-key
            - name: MODULR_API_SERCET
              valueFrom:
                secretKeyRef:
                  name: cs-secrets
                  key: modulr-api-secret
            - name: DB_TYPE
              value: "postgres"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: cs-secrets
                  key: postgres-host
            - name: DB_HOST_R1
              valueFrom:
                secretKeyRef:
                  name: cs-secrets
                  key: postgres-host-r1
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: cs-secrets
                  key: postgres-port
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cs-secrets
                  key: postgres-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cs-secrets
                  key: postgres-password
            - name: DB_NAME
              value: "syllotransfast"
            - name: DB_SYNC_ENABLED
              value: "false"
            - name: DB_MIGRATIONS_ENABLED
              value: "true"
            - name: DB_LOGGING
              value: "false"
            - name: MQ_URL
              valueFrom:
                secretKeyRef:
                  name: cs-secrets
                  key: mq-url
            - name: PFS_ORGANIZATION_INTERNAL_ID
              value: "NOT SET"
            - name: FS_EUR_API_BASE
              value: "NOT SET"
            - name: PFS_EUR_API_PAYMENT
              value: "NOT SET"
            - name: PFS_VENDOR_ID
              value: "NOT SET"
            - name: PFS_ENCRIPTION_KEY
              value: "NOT SET"
            - name: FS_EUR_API_ORIGIN
              value: "NOT SET"
            - name: FS_EUR_API_MESSAGE
              value: "NOT SET"
            - name: FS_EUR_API_USERNAME
              value: "NOT SET"
            - name: FS_EUR_API_PASSWORD
              value: "NOT SET"
            - name: FS_EUR_API_BIN
              value: "123456789"
            - name: FS_EUR_API_DISTRIBUTOR_CODE
              value: "123456789"
            - name: FS_GBP_API_BASE
              value: "NOT SET"
            - name: PFS_GBP_API_PAYMENT
              value: "NOT SET"
            - name: FS_GBP_API_ORIGIN
              value: "NOT SET"
            - name: FS_GBP_API_MESSAGE
              value: "NOT SET"
            - name: FS_GBP_API_USERNAME
              value: "NOT SET"
            - name: FS_GBP_API_PASSWORD
              value: "NOT SET"
            - name: FS_GBP_API_BIN
              value: "123456789"
            - name: FS_GBP_API_DISTRIBUTOR_CODE
              value: "123456789"
            - name: RAILSBANK_API_BASE_URL
              value: "https://play.railsbank.com"
            - name: RAILSBANK_API_ROLE
              value: "customer-admin"
            - name: RAILSBANK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cs-secrets
                  key: railsbank-api-key
            - name: RAILSBANK_PARTNER_PRODUCT_GBP
              value: "PayrNet-GBP-2"
            - name: RAILSBANK_FEES_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: cs-secrets
                  key: railsbank-fees-account
            - name: ACCOMPLISH_API_BASE_URL
              value: "https://api.nuvopay.com"
            - name: ACCOMPLISH_GRANT_TYPE
              value: "program_credential"
            - name: ACCOMPLISH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cs-secrets
                  key: accomplish-username
            - name: ACCOMPLISH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cs-secrets
                  key: accomplish-password
            - name: ACCOMPLISH_PROGRAM_ID
              valueFrom:
                secretKeyRef:
                  name: cs-secrets
                  key: accomplish-program-id
            - name: ACCOMPLISH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cs-secrets
                  key: accomplish-api-key
            - name: ACCOMPLISH_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: cs-secrets
                  key: accomplish-encryption-key
            - name: ACCOMPLISH_ACCOUNT_EUR_BIN_ID
              value: "4678"
            - name: ACCOMPLISH_ACCOUNT_GBP_BIN_ID
              value: "4677"
            - name: ACCOMPLISH_EWALL_EUR_BIN_ID
              value: "4729"
            - name: ACCOMPLISH_EWALL_GBP_BIN_ID
              value: "4730"
            - name: ACCOMPLISH_FULFILMENT_CONFIG_ID
              value: "103"
            - name: MICROSOFT_TEAMS_WEBHOOKS_ENABLED
              value: "false"
            - name: MICROSOFT_TEAMS_WEBHOOK_URL
              value: "https://not.configured.com"
            - name: GRPC_VERBOSITY
              value: "DEBUG"
            - name: TOP_UP_MIN_AMOUNT_EUR
              value: "10"
            - name: HOST_URL
              value: "https://api.transfast.stage.pannovate.net"
            - name: GPS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cs-secrets
                  key: gps_username
            - name: GPS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cs-secrets
                  key: gps_password
            - name: GPS_WSDL_URL
              value: "http://10.18.150.22:13682/service.asmx?wsdl" # This proxies to "https://pwsv7rrlo4.globalprocessing.net:13682/service.asmx"
            - name: GPS_ISS_CODE
              value: "TFS"
            - name: PORT
              value: "10003"
            - name: NO_COLOR
              value: "true"
            - name: CLIENT
              value: "TRANSFAST"
            - name: MASK_PAN_LENGTH
              value: "4"
            - name: SYLLO_LOG_LEVEL
              value: "2"
            - name: PLUGINS
              value: "@syllo/transfast,@syllo/chat"
            - name: DEBUG
              value: "false"

