apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: kube-system
  labels:
    app.kubernetes.io/name: fluentbit
spec:
  selector:
    matchLabels:
      name: fluentbit
  template:
    metadata:
      labels:
        name: fluentbit
    spec:
      serviceAccountName: fluent-bit
      containers:
        - name: aws-for-fluent-bit
          # Image should be from output of the AWS Systems Manager command 'aws ssm get-parameter ......'
          #     for example: 906394416424.dkr.ecr.eu-west-1.amazonaws.com/aws-for-fluent-bit:latest
          image: 906394416424.dkr.ecr.eu-west-1.amazonaws.com/aws-for-fluent-bit:latest
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
            - name: mnt
              mountPath: /mnt
              readOnly: true
          resources:
            # Theire recommendations: https://github.com/fluent/fluent-bit-kubernetes-logging/blob/d0b012e567d5b69afb85bc60ad1ff98c0da72835/output/kafka/fluent-bit-ds.yaml#L38
            limits:
              cpu: 100m # They recommend 5m
              memory: 256Mi # They recommend 60Mi
            requests:
              cpu: 50m # They reccommend 5m
              memory: 100Mi # They recommend 10Mi
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
        - name: mnt
          hostPath:
            path: /mnt
