apiVersion: v1
kind: Service
metadata:
  name: tfs-pubsub-service
  namespace: tfs-pubsub
  labels:
    app.kubernetes.io/name: pubsub
    app: pubsub
spec:
  selector:
    app: pubsub
  ports:
    - name: pubsub-port
      protocol: TCP
      port: 10009
      targetPort: 10009
