apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfs-config-deployment
  labels:
    app.kubernetes.io/name: config
    app: config
  namespace: tfs-config
  annotations:
    linkerd.io/inject: enabled
spec:
  selector:
    matchLabels:
      app: config
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - name: syllo-config
          image: 309602515679.dkr.ecr.eu-west-1.amazonaws.com/syllo-config:1.8.3
          imagePullPolicy: Always
          resources:
            limits:
              memory: 200Mi
              cpu: "0.2"
            requests:
              memory: 100Mi
              cpu: "0.1"
          ports:
            - containerPort: 10008
          env:
            - name: npm_package_version
              value: "1.8.3"
            - name: ENVIRONMENT
              value: "production"
            - name: GRPC_SERVER_URL
              value: "0.0.0.0:10008"
            - name: HTTP_SERVER_PORT
              value: "1111"
            - name: AS_URL
              value: "172.20.49.111:10004"
            - name: DB_TYPE
              value: "postgres"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: postgres-host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: postgres-port
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: postgres-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: postgres-password
            - name: DB_NAME
              value: "syllotransfast"
            - name: DB_SYNC_ENABLED
              value: "false"
            - name: DB_MIGRATIONS_ENABLED
              value: "true"
            - name: DB_LOGGING
              value: "true"
            - name: MQ_URL
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: mq-url
            - name: PUBSUB_URL
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: redis-url
            - name: NO_COLOR
              value: "true"
            - name: CLIENT
              value: "TRANSFAST"
            - name: DEBUG
              value: "false"

