apiVersion: v1
kind: Service
metadata:
  name: tfs-kyc-service
  namespace: tfs-kyc
  labels:
    app.kubernetes.io/name: kyc
    app: kyc
spec:
  selector:
    app: kyc
  ports:
    - name: kyc-port
      protocol: TCP
      port: 10002
      targetPort: 10002
