apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfs-els-deployment
  labels:
    app.kubernetes.io/name: els
    app: els
  namespace: tfs-els
  annotations:
    linkerd.io/inject: enabled
spec:
  selector:
    matchLabels:
      app: els
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: els
    spec:
      containers:
        - name: syllo-els
          image: 309602515679.dkr.ecr.eu-west-1.amazonaws.com/syllo-els:1.8.3
          imagePullPolicy: Always
          resources:
            limits:
              memory: 200Mi
              cpu: "0.2"
            requests:
              memory: 100Mi
              cpu: "0.1"
          ports:
            - containerPort: 10006
          env:
            - name: npm_package_version
              value: "1.8.3"
            - name: ENVIRONMENT
              value: "production"
            - name: GRPC_HOST
              value: "0.0.0.0:10006"
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: els-secrets
                  key: mongo-uri
            - name: MQ_URL
              valueFrom:
                secretKeyRef:
                  name: els-secrets
                  key: mq-url
            - name: PUBSUB_URL
              valueFrom:
                secretKeyRef:
                  name: els-secrets
                  key: redis-url
            - name: CONFIG_URL
              value: "172.20.176.186:10008"
            - name: FS_URL
              value: "172.20.142.166:10007"
            - name: NO_COLOR
              value: "true"
            - name: CLIENT
              value: "TRANSFAST"
            - name: DEBUG
              value: "false"

