apiVersion: v1
kind: Service
metadata:
  name: tfs-mps-service
  namespace: tfs-mps
spec:
  selector:
    app: mps
  ports:
    - name: mps-port
      protocol: TCP
      port: 10005
      targetPort: 10005
