apiVersion: v1
kind: Service
metadata:
  name: tfs-cs-service
  namespace: tfs-cs
  labels:
    app.kubernetes.io/name: cs
    app: cs
spec:
  selector:
    app: cs
  ports:
    - name: cs-port
      protocol: TCP
      port: 10003
      targetPort: 10003
