---
# This role will create a user on the host with user name userName. For
# this user, an entry in the sudoers file is generated which gives the user
# full sudo privileges without password authentication. In addition,
# we copy the SSH key {{userPrivateKeyFile}}.pub to the authorized_keys
# file of the new user, so that it can be used to log in via SSH
# public key authorization
- name: Create a default user on the host
  ansible.builtin.user:
    name: "{{ userName }}"
    comment: "Syllo main user"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    shell: "/bin/bash"
    state: present
- name: Create home directory for the new user
  file:
    path: /home/{{ userName }}/.ssh
    group: "{{ userName }}"
    owner: "{{ userName }}"
    mode: 0700
    state: directory
- name: Distribute ssh key
  copy:
    src: "/root/.ssh/authorized_keys"
    dest: "/home/{{ userName }}/.ssh/authorized_keys"
    remote_src: true
    mode: 0700
    owner: "{{ userName }}"
    group: "{{ userName }}"
- name: Add newly created user to sudoers file
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    line: "{{ userName }}      ALL = NOPASSWD: ALL"
    validate: /usr/sbin/visudo -cf %s
- name: Create some BASH Aliases
  ansible.builtin.lineinfile:
    path: "/home/{{ userName }}/.bash_aliases"
    create: yes
    state: present
    line: "alias ll='ls -al'\nalias la='ls -A'\nalias l='ls -CF'"
    mode: "0644"
    owner: "{{ userName }}"
    group: "{{ userName }}"
- name: Remove .bash_logout
  ansible.builtin.file:
    path: "/home/{{userName}}/.bash_logout"
    state: absent
