apiVersion: v1
kind: Service
metadata:
  name: tfs-config-service
  namespace: tfs-config
spec:
  selector:
    app: config
  ports:
    - name: config-port
      protocol: TCP
      port: 10008
      targetPort: 10008
