apiVersion: v1
kind: Service
metadata:
  name: tfs-fs-service
  namespace: tfs-fs
spec:
  selector:
    app: fs
  ports:
    - name: fs-port
      protocol: TCP
      port: 10007
      targetPort: 10007
