apiVersion: v1
kind: Service
metadata:
  name: tfs-as-service
  namespace: tfs-as
spec:
  selector:
    app: as
  ports:
    - name: as-port
      protocol: TCP
      port: 10004
      targetPort: 10004
