apiVersion: v1
kind: Service
metadata:
  name: tfs-webhook-service
  namespace: tfs-webhook
  labels:
    app.kubernetes.io/name: webhook
    app: webhook
spec:
  selector:
    app: webhook
  ports:
    - name: webhook-port
      protocol: TCP
      port: 10010
      targetPort: 10010
